### ISSUE TITLE
Action not failing on errors

### ISSUE THREAD

**Issue by dasheck0** [wzieba/AppCenter-Github-Action#22]
I used this action in one of my workflows and ran into an error. I just forgot to add the token as github secret. However, the workflow finished successfully despite the error. I then went to App Center and searched for the release. After a while I checked the workflow logs. The error was displayed correctly (I was not logged in). 

```
Error: Command 'appcenter distribute release' requires a logged in user. Use the 'appcenter login' command to log in.
```

But as I stated earlier the action finished without failing, which is not correct. The expected behaviour is that the action fails, resulting in a failing workflow.

**Comment by mam17** [comment]
+1

**Comment by wzieba** [comment]
Thanks, @dasheck0 @mam17 for feedback, sure: the action should file. I'll investigate why it doesn't and try to find some fix for that.
