### ISSUE TITLE
Response status code: 404

### ISSUE THREAD

**Issue by Lucasc23051994** [wzieba/AppCenter-Github-Action#30]
Hi there! I´m using that action but everytime my run fails...it looks like it can´t find my .apk, also, it shows 2 URL´s with some messages:

https://api.appcenter.ms/v0.1/apps/Lucas.Azevedo.23/mediservice/distribution_groups/Collaborators/members

https://api.appcenter.ms/v0.1/apps/Lucas.Azevedo.23/mediservice/release_uploads

Also, I run the action with the debug flag and here´s what I´ve got:

Run wzieba/AppCenter-Github-Action@v1
  with:
    appName: Lucas.Azevedo.23/mediservice
    token: ***
    group: Collaborators
    file: /home/runner/work/mediservice/mediservice/platforms/android/app/build/outputs/apk/debug/app-debug.apk
    notifyTesters: true
    debug: true
  env:
    JAVA_HOME_8.0.265_x64: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.265/x64
    JAVA_HOME_8_0_265_X64: /opt/hostedtoolcache/jdk/8.0.265/x64
/usr/bin/docker run --name aac2aa315255cf0cc94afbab7645f26ad04118_d22213 --label aac2aa --workdir /github/workspace --rm -e JAVA_HOME_8.0.265_x64 -e JAVA_HOME -e JAVA_HOME_8_0_265_X64 -e INPUT_APPNAME -e INPUT_TOKEN -e INPUT_GROUP -e INPUT_FILE -e INPUT_NOTIFYTESTERS -e INPUT_DEBUG -e INPUT_BUILDVERSION -e INPUT_BUILDNUMBER -e INPUT_RELEASENOTES -e INPUT_GITRELEASENOTES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mediservice/mediservice":"/github/workspace" aac2aa:315255cf0cc94afbab7645f26ad04118
Using appcenter-cli version: 2.5.4
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Lucas.Azevedo.23/mediservice/distribution_groups/Collaborators/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.4 NodeJS/v12.10.0 linux/5.4.0-1025-azure",
    "x-api-token": "***"
  },
  "body": null
}
Response status code: 404
Body: {"message":"Not found. Correlation ID: c4a26aec-d182-4249-9a2e-a5d47de87cb5","statusCode":404,"code":"Not Found"}
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Lucas.Azevedo.23/mediservice/release_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.4 NodeJS/v12.10.0 linux/5.4.0-1025-azure",
    "x-api-token": "***"
  },
  "body": null
}
Response status code: 404
Body: {"message":"Not found. Correlation ID: 62517c7f-f749-4dd2-a9e9-215baf4feb00","statusCode":404,"code":"Not Found"}
Error: failed to create release upload for /github/workspace/platforms/android/app/build/outputs/apk/debug/app-debug.apk

I´ve tried all the paths that I can, but everytime the run fails...

Any idea how to help me with this issue?

Thank you all in advance.

**Comment by wzieba** [comment]
hi @Lucasc23051994, were you able to resolve your issue?

**Comment by montrimas** [comment]
Hello, we are having the same issue on our workflow right now.

**Comment by wzieba** [comment]
Sure, could you please re-run workflow with `[debug](https://github.com/wzieba/AppCenter-Github-Action#debug)` option and print stacktrace?

**Comment by Lucasc23051994** [comment]
Hi @wzieba, not yet ): I really don´t know why it´s happening...

**Comment by wzieba** [comment]
Guys, can you please share some more details for this issue? Like mentioned above stacktrace from build with `debug: true` ?

The logs in issues descriptions look like there's maybe an invalid `appName` attribute. Can you please ensure you set the correct one?

**Comment by Lucasc23051994** [comment]
Hello @wzieba!

So, I´m using my personal App Center for testing, and I used in the code "appName: Lucas.Azevedo.23/mediservice", I´ve confirmed the name at App Center.

I´ll run the script one more time and I´ll pass the log here, I think the last time I run it the error was about the .apk location, and the path is right too.

I´ll keep in touch.

Best regards.

**Comment by Lucasc23051994** [comment]
Hey @wzieba, here´s the updated log for the script:

Run wzieba/AppCenter-Github-Action@v1
  with:
    appName: Lucas.Azevedo.23/mediservice
    token: ***
    group: Collaborators
    file: /home/runner/work/mediservice/mediservice/platforms/android/app/build/outputs/apk/debug/app-debug.apk
    notifyTesters: true
    debug: true
  env:
    JAVA_HOME_8.0.275_x64: /opt/hostedtoolcache/jdk/8.0.275/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.275/x64
    JAVA_HOME_8_0_275_X64: /opt/hostedtoolcache/jdk/8.0.275/x64
/usr/bin/docker run --name cc4956585282cd93144dd193f174a9504d60f4_bf2705 --label cc4956 --workdir /github/workspace --rm -e JAVA_HOME_8.0.275_x64 -e JAVA_HOME -e JAVA_HOME_8_0_275_X64 -e INPUT_APPNAME -e INPUT_TOKEN -e INPUT_GROUP -e INPUT_FILE -e INPUT_NOTIFYTESTERS -e INPUT_DEBUG -e INPUT_BUILDVERSION -e INPUT_BUILDNUMBER -e INPUT_RELEASENOTES -e INPUT_GITRELEASENOTES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mediservice/mediservice":"/github/workspace" cc4956:585282cd93144dd193f174a9504d60f4
Using appcenter-cli version: 2.7.3
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Lucas.Azevedo.23/mediservice/distribution_groups/Collaborators/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.7.3 NodeJS/v12.10.0 linux/5.4.0-1032-azure",
    "x-api-token": "***"
  },
  "body": null
}
Response status code: 404
Body: {"message":"Not found. Correlation ID: 8223681f-d821-4922-b6f1-5c6f10922c84","statusCode":404,"code":"Not Found"}
Error: failed to create release upload for /github/workspace/platforms/android/app/build/outputs/apk/debug/app-debug.apk. Not found. Correlation ID: 547ce9d6-8d7e-4767-a7ec-5816d25e7027

I´ve checked the path and it´s right, I used the path that is generated at the app build.

Thanks in advance.

**Comment by wzieba** [comment]
Hi, I'm cleaning issues in this repo and I see I must've missed the reply. Sorry for that @Lucasc23051994 ! I hope you resolved your issue.
