### ISSUE TITLE
AppCenter deployment failed today

### ISSUE THREAD

**Issue by tmorone-rezi** [wzieba/AppCenter-Github-Action#32]
I have not diagnosed this yet, but I did notice the CLI was upgraded but not released yet. My build failed today on both ios and android. Do we need this new CLI?

Error: failed to create release upload for release.ipa

**Comment by tmorone-rezi** [comment]
Looks like a problem with AppCenter. Major outage today.
https://status.appcenter.ms/#

**Comment by wzieba** [comment]
hi @tmorone-rezi, thanks for reporting. Indeed, AppCenter had outage today. @xom9ikk prepared PR #31 with bumping app center to 2.7.x, as suggested on AppCenter's status page.

![image](https://user-images.githubusercontent.com/5845095/101550574-d0cba880-39af-11eb-84c6-f94e7eeb7c90.png)

Either way, everything should work fine as AppCenter reports "All Systems Operational". Thank you though for reporting this issue. I don't use this action on daily basis so I can't react to such issues if I'm not aware that something broke.
