### ISSUE TITLE
Please use the latest version of the App Center CLI

### ISSUE THREAD

**Issue by VladSumtsov** [wzieba/AppCenter-Github-Action#33]
Hi!

Previously working fine scripts are failing now. 
Looks like appcenter-cli 2.5.4 backend API is deprecated now and the appcenter-cli needs to be updated to the latest 2.7.3 version in the plugin.

`/usr/bin/docker run --name afc9db4c5041c5805d342d63297a46_33b69f --label 179394 --workdir /github/workspace --rm -e JAVA_HOME_8.0.275_x64 -e JAVA_HOME -e JAVA_HOME_8_0_275_X64 -e SIGNED_RELEASE_FILE -e RELEASE_NOTES -e INPUT_APPNAME -e INPUT_TOKEN -e INPUT_GROUP -e INPUT_FILE -e INPUT_NOTIFYTESTERS -e INPUT_RELEASENOTES -e INPUT_DEBUG -e INPUT_BUILDVERSION -e INPUT_BUILDNUMBER -e INPUT_GITRELEASENOTES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/xmp2go-***/xmp2go-***":"/github/workspace" 179394:52afc9db4c5041c5805d342d63297a46

Using appcenter-cli version: 2.5.4

logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/CoreWillSoft-GmbH/XMP2GO-1/distribution_groups/Testers/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.4 NodeJS/v12.10.0 linux/5.4.0-1031-azure",
    "x-api-token": "***"
  },
  "body": null
}

Response status code: 200
Body: [{"id":"b8080893-1f78-4918-8680-820e495209d2","display_name":"Irina Lubenets","email":"irina.lubenets@corewillsoft.com","name":"irina.lubenets-corewillsoft.com","avatar_url":null,"can_change_password":false,"created_at":"2020-09-22T11:09:24.000Z","origin":"appcenter"},{"id":"7b7b39f0-a86c-4978-a629-be6343ec1e41","display_name":"Vladyslav Sumtsov","email":"vlad.sumtsov@corewillsoft.com","name":"vlad.sumtsov-corewillsoft.com","avatar_url":null,"can_change_password":false,"created_at":"2019-09-05T14:41:21.000Z","origin":"hockeyapp"},{"id":"95f8a248-29d6-432b-87d2-e5e03bafaa6e","display_name":"Marie Dunaevskaya","email":"marie.dunaevskaya@corewillsoft.com","name":"marie.dunaevskaya-corewillsoft.com","avatar_url":null,"can_change_password":false,"created_at":"2020-04-07T12:07:38.000Z","origin":"appcenter"},{"id":"3004e479-6779-4dd5-9c8f-fd29627c087c","display_name":"Aleksandr Kozlov","email":"alex.kozlov@corewillsoft.com","name":"alex.kozlov-corewillsoft.com","avatar_url":null,"can_change_password":false,"created_at":"2020-08-21T14:04:12.000Z","origin":"appcenter"}]

logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/CoreWillSoft-GmbH/XMP2GO-1/release_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.4 NodeJS/v12.10.0 linux/5.4.0-1031-azure",
    "x-api-token": "***"
  },
  "body": null
}

Response status code: 410
Body: {"code":"gone","message":"This API is deprecated. Please use the latest version of the App Center CLI: https://github.com/microsoft/appcenter-cli, or if you need a custom script please use the CLI as the basis for your implementation. (Support ID: b16fa247-3d47-4cab-b4fb-699b10fa7f9b)"}
Error: failed to create release upload for app/build/outputs/apk/beta/XMP2GO-beta-signed.apk`

**Comment by wzieba** [comment]
Hi, thanks for the report. Yesterday I've pushed a new release `v.1.3.2` which points to `appcenter-cli` 2.7.3.

I forgot to update `v1` tag though, just did it so if you reference to action by `@v1` tag please re-run your workflow.
