### ISSUE TITLE
Feature Request: Support Mac OS runner

### ISSUE THREAD

**Issue by harry248** [wzieba/AppCenter-Github-Action#39]
Would be nice if this action had support for a Mac OS runner, although I have no idea how big the effort is.

**Comment by deathemperor** [comment]
Would love this too

**Comment by Massad** [comment]
You could use the sample from here: https://github.com/testappio/github-action

**Comment by wzieba** [comment]
Thanks for the idea but this is not planned. The reason for that is that I'd prefer to keep this action Docker-based and [Mac OS runner is not supporting Docker-based actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions). 

You can always pass the artifact to a Linux-based job. See this snippet of a similar action: https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/24#issuecomment-769731085
