### ISSUE TITLE
Unable to find apk

### ISSUE THREAD

**Issue by jom16antonio** [wzieba/AppCenter-Github-Action#41]
An error results when trying to upload to AppCenter
Command Failure at Error: ENOENT: no such file or directory, stat 'app/build/outputs/apk/release/Nimble_build*-qa-release.apk'

I use asterisk to replace the number values in the name. Also, I have a flavor (qa)
so should it be app/build/outputs/apk/qa/release 

even if I add the /qa in the path above, i get the same mo such file error

**Comment by mateuszkwiecinski** [comment]
@jom16antonio 
>I use asterisk to replace the number values in the name

I don't think that's supported and I don't think it will be - what behavior would you expect if there were multiple files found? 

You have to point at existing file by its name. I assume "number values" is the app version - you can set the version as a step output using Github Actions syntax: https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions and then consume it as `app/build/outputs/apk/release/Nimble_build{{ steps.your_build_step.outpus.app_version }}-qa-release.apk` (or you can set the apk path as the output, which actually seems the most common practice (i.e. Fastlane doest that))

**Comment by jom16antonio** [comment]
@mateuszkwiecinski 
Thank you for your comment. That makes sense. Using a wildchar character will not work. I just renamed the file before calling it. And it now works. thanks
