### ISSUE TITLE
Requires Login?  Nothing in Script shows how to do this.

### ISSUE THREAD

**Issue by grndvl1** [wzieba/AppCenter-Github-Action#46]
Error: Command 'appcenter distribute release' requires a logged in user. Use the 'appcenter login' command to log in. 

Nothing in command shows how to do this, thought I just needed the Token which is in my github secrets for repo.

**Comment by wzieba** [comment]
There's no need for anything more than having a token. Maybe the token is invalid or there's a typo in Github environmental variable?

**Comment by grndvl1** [comment]
Okay now I can but now it says it can't find the file apk to upload.  Can you steer as to how to find that location on the VM after it checks the repo out?  I've tried a few things and looked at the logs to find the directory structure but I am at a loss.

**Comment by wzieba** [comment]
By default, it should be in the application module directory and then `build/outputs/apk/<build variant names>/<name of the project with build variant names>.apk`.

One can see that the path highly depends on the project-specific details and configuration so it's difficult to provide meaningful instructions.

But I agree it would be nice if the action could look for any `.apk` (or other) files and print paths to make it easier for configuration. There's an issue for that in a twin action, maybe I should revisit it: https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/44

Thanks for the feedback! I'll close this issue but if you need any assistance, feel free to reopen it.
