### ISSUE TITLE
Command distribute...is invalid

### ISSUE THREAD

**Issue by harry248** [wzieba/AppCenter-Github-Action#54]
The action has worked well for us for 2 years, but since yesterday our builds have been failing with the error:

`Error: Command distribute release --token *** --app XXX --group XXX --file /github/workspace/androidApp/build/outputs/apk/develop/release/androidApp-develop-release-unsigned-signed.apk --release notes --silent --debug is invalid`

We have not changed anything in the action configuration or in AppCenter and therefore cannot explain the error.

Maybe related to https://github.com/microsoft/appcenter-cli/issues/2397?

**Comment by bennettp123** [comment]
@harry248 thanks for the hint about the upstream issue — it seems to work fine after updating the base image to node 20.

I've created a pull-request that hopefully fixes the problem.

**Comment by jkraus-wyn** [comment]
Hi, same issue for us :), can you let us know when it can be done?

**Comment by wzieba** [comment]
The fix has been released in [v1.3.4](https://github.com/wzieba/AppCenter-Github-Action/releases/tag/v1.3.4). It's also available if you use `v1` tag.

Thank you @bennettp123 for your PR and everyone who reported the issue!
