### ISSUE TITLE
Error: Command distribute release is invalid

### ISSUE THREAD

**Issue by whiteLT** [wzieba/AppCenter-Github-Action#59]
Hello, I've been using your action for some time and all was working good, but today it stopped working. I get this error:
`
Error: Command distribute release --token *** --app App/Test --group Collaborators --file build/app/outputs/flutter-apk/app.apk --release-notes  is invalid`

yml:

```
      - name: upload artifact to App Center
        uses:  local/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.UPLOAD_NAME }}
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: build/app/outputs/flutter-apk/${{ env.UPLOAD_APK_NAME }}
          notifyTesters: true
          debug: false

```

Any tips why it stopped working? Or how to get more info on the error

**Comment by nathenxbrewer** [comment]
I am seeing this issue as well. I have a failed build from last week due to this.

**Comment by nathenxbrewer** [comment]
Updated to 1.3.4 and the issue has been resolved. 
`uses: wzieba/AppCenter-Github-Action@v1.3.4`

**Comment by whiteLT** [comment]
@nathenxbrewer Thank you!
