### ISSUE TITLE
Desktop Application

### ISSUE THREAD

**Issue by AmeerMansourWSP** [wzieba/AppCenter-Github-Action#64]
I used to use app center to distribute my desktop application as ZIP file or Exe using Azure pipelines. will i be able to do the same with this Action ? or it only works for APK & ipa

**Comment by ivan-coder** [comment]
I'm using this action to upload zip files, everything works fine, nothing special you need to do as far as I'm aware.

**Comment by AmeerMansourWSP** [comment]
thanks i will try that out.
